# -*- coding: utf-8 -*-
"""movierecommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oNLFrLOMtUvvg7xPP1emVqHYQ9aElklP

# *TITLE*
**MOVIE RECOMMENDATION**
"""

import pandas as pd

import numpy as np

"""# **IMPORT DATASET**"""

df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Movies%20Recommendation.csv')

df.head()

df.info()

df.shape

df.columns

"""# **GET FEATURE SELECTION**"""

df_features=df[['Movie_Genre','Movie_Keywords', 'Movie_Tagline', 'Movie_Cast','Movie_Director']].fillna('')

df_features.shape

df_features

x=df_features['Movie_Genre']+' '+df_features['Movie_Keywords']+' '+df_features['Movie_Tagline']+' '+df_features['Movie_Cast']+' '+df_features['Movie_Director']

x

x.shape

"""# **Get Features Text Conversion to Tokens**"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

x=tfidf.fit_transform(x)

x.shape

print(x)

"""# **Get Similarity Score using Cosine Similarity**"""

from sklearn.metrics.pairwise import cosine_similarity

similarity_score=cosine_similarity(x)

similarity_score

similarity_score.shape

"""# **Get Movie Name as Input from User and Validate for Closest Spelling**"""

#favaourite_movie_name=fmn
fmn=input('ENTER YOUR FAVOURITE MOVIE:')

tl=df['Movie_Title'].tolist()

import difflib

movie_rec=difflib.get_close_matches(fmn,tl)
print (movie_rec)

close_match=movie_rec[0]
print(close_match)

index_cm=df[df.Movie_Title == close_match]['Movie_ID'].values[0]
print(index_cm)

recommendation_score =list(enumerate(similarity_score[index_cm]))
print (recommendation_score)

len(recommendation_score)

"""# **Get All Movies Sort Based on Recommendation Score wrt Favourite Movie**"""

sorted_movies =sorted(recommendation_score,key=lambda  x:x[1],reverse=True)
print(sorted_movies)

print('Top 30 Movies Suggested for you: \n')
i=1
for movie in sorted_movies:
  index=movie[0]
  title_from_index=df[df.index==index]['Movie_Title'].values[0]
  if(i<31):
    print(i,'.',title_from_index)
    i+=1

"""# **Top 10 Movie Recommendation System**"""

movie_name= input('Enter your favourite movie name: ')

list_of_all_titles =df['Movie_Title'].tolist()

find_close_match= difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]

index_of_movie =df[df.Movie_Title==close_match]['Movie_ID'].values[0]

recommendation_score=list(enumerate(similarity_score[index_of_movie]))

sorted_similar_movies=sorted(recommendation_score,key=lambda  x:x[1],reverse=True)

print('Top 10 movies suggested for you: \n ')
i=1
for movie in sorted_similar_movies:
  index=movie[0]

  title_from_index=df[df.Movie_ID==index]['Movie_Title'].values
  if(i<11):
    print(i,'.',title_from_index)
    i+=1

